name: Normalize web/web.srt line endings to LF

on:
  push:
    paths:
      - 'web/web.srt'

permissions:
  contents: write

jobs:
  normalize-srt:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get last commit info for web/web.srt
        id: last_commit
        run: |
          FILE=web/web.srt
          LAST_COMMIT_MSG=$(git log -n 1 --pretty=format:%B -- "$FILE" || true)
          if [ -z "$LAST_COMMIT_MSG" ]; then
            LAST_COMMIT_MSG="Normalize line endings in web/web.srt"
          fi
          echo "$LAST_COMMIT_MSG" > commit_message.txt
          LAST_AUTHOR_NAME=$(git log -n 1 --pretty=format:%an -- "$FILE" || echo "unknown")
          LAST_AUTHOR_EMAIL=$(git log -n 1 --pretty=format:%ae -- "$FILE" || echo "unknown@example.com")
          echo "::set-output name=message_file::commit_message.txt"
          echo "::set-output name=author_name::${LAST_AUTHOR_NAME}"
          echo "::set-output name=author_email::${LAST_AUTHOR_EMAIL}"

      - name: Check and normalize line endings
        id: check
        run: |
          FILE=web/web.srt
          if [ ! -f "$FILE" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          if grep -q $'\r' "$FILE"; then
            perl -0777 -pe 's/\r\n/\n/g; s/\r/\n/g' "$FILE" > "${FILE}.normalized"
            mv "${FILE}.normalized" "$FILE"
            git add "$FILE"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and force-push if changed
        if: steps.check.outputs.changed == 'true'
        env:
          MESSAGE_FILE: ${{ steps.last_commit.outputs.message_file }}
          ORIGINAL_AUTHOR_NAME: ${{ steps.last_commit.outputs.author_name }}
          ORIGINAL_AUTHOR_EMAIL: ${{ steps.last_commit.outputs.author_email }}
        run: |
          FILE=web/web.srt
          if [ ! -f "${MESSAGE_FILE}" ]; then
            echo "Message file ${MESSAGE_FILE} not found"; exit 1
          fi

          # 将 author 和 committer 同设为原始作者（保留作者与提交者一致）
          export GIT_AUTHOR_NAME="${ORIGINAL_AUTHOR_NAME}"
          export GIT_AUTHOR_EMAIL="${ORIGINAL_AUTHOR_EMAIL}"
          export GIT_COMMITTER_NAME="${ORIGINAL_AUTHOR_NAME}"
          export GIT_COMMITTER_EMAIL="${ORIGINAL_AUTHOR_EMAIL}"

          # 提交使用 -F 指定包含完整 message（含 body）的文件
          git commit -F "${MESSAGE_FILE}" -- "$FILE" || { echo "commit failed or nothing to commit"; exit 1; }

          BRANCH="${GITHUB_REF#refs/heads/}"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" "HEAD:${BRANCH}" --force
